#"Map":
# - changed-files:
#   - any-glob-to-any-file: "Resources/Maps/**/*.yml" # All .yml files in the Resources/Maps directory, recursive.

"Карты":
- changed-files:
  - any-glob-to-any-file:
    - "Resources/Maps/**/*.yml" # Grid Files
    - "Resources/Prototypes/Maps/**/*.yml" # Prototypes Files
    - "Resources/Prototypes/**/Maps/**/*.yml" # Prototypes Files

"Текстуры":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.rsi/*.png"
    - "**/*.rsi/*.json"

"UI":
- changed-files:
  - any-glob-to-any-file: "**/*.xaml*"

"C#":
- changed-files:
  - any-glob-to-any-file: "**/*.cs"

"Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Звук":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"Документация":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.xml"
    - "**/*.md"

"Переводы":
- changed-files:
  - any-glob-to-any-file: "Resources/Locale/**/*.ftl"

"YML":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.yml"
    - all-globs-to-any-file:
      - "!Resources/Maps/**/*.yml"
      - "!Resources/Prototypes/Maps/**/*.yml"
      - "!Resources/Prototypes/**/Maps/**/*.yml"

"База Данных":
- changed-files:
  - any-glob-to-any-file: "Content.Server.Database/Migrations/**/*.cs"
