contact_links:
- name: Сообщить об уязвимости
  url: https://github.com/Legacy-Of-Paradise/main-erp/blob/master/SECURITY.md
  about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности.
- name: Предложение
  url: https://wiki.legacyofparadise.space/discord/
  about: Свои предложения можете оставлять в соответствующем канале Discord.
