name: Test Packaging Secrets

on:
  workflow_dispatch:
#   push:
#     branches: [ master, staging, trying ]
#     paths:
#     - '**.cs'
#     - '**.csproj'
#     - '**.sln'
#     - '**.git**'
#     - '**.yml'
#     # no docs on which one of these is supposed to work, so
#     # why not just do both
#     - 'RobustToolbox'
#     - 'RobustToolbox/**'

jobs:
  build:
    name: Test Packaging Secrets
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'FrontierATC' && github.actor != 'LOPBot' && github.repository == 'Legacy-Of-Paradise/main-erp'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3.6.0

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Download parts
      run: |
        git clone ${{ secrets.SecretsMain }}
        mv Secrets/_PrivateResources/_Private Resources/Prototypes/
        mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
        mv Secrets/_PrivateShared Content.Shared/_PrivateShared
        mv Secrets/_PrivateServer Content.Server/_PrivateServer
        mv Secrets/_PrivateClient Content.Client/_PrivateClient

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release
