name: RSI Validator Secrets

on:
  workflow_dispatch:
  # push:
  #   branches: [ master, staging, trying ]
  #   paths:
  #     - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'FrontierATC' && github.actor != 'LOPBot' && github.repository == 'Legacy-Of-Paradise/main-erp'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Download parts
        run: |
          git clone ${{ secrets.SecretsMain }}
          mv Secrets/_PrivateResources/_Private Resources/Prototypes/
          mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
          mv Secrets/_PrivateShared Content.Shared/_PrivateShared
          mv Secrets/_PrivateServer Content.Server/_PrivateServer
          mv Secrets/_PrivateClient Content.Client/_PrivateClient
      - name: Setup Submodule
        run: git submodule update --init
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
